name: Deploy Files to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      host_name:
        description: 'Host name to deploy files for'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Prepare files for deployment
        run: |
          mkdir public
          cp -r ./${{ github.event.inputs.host_name }}/* public/
          echo "${{ github.event.inputs.host_name }}.github.io" > public/CNAME

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add public
          git commit -m "Deploy ${{ github.event.inputs.host_name }} files to GitHub Pages"
          git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" main:gh-pages
