name: Serve Files

on:
  workflow_dispatch:
    inputs:
      user_type:
        description: 'User type'
        required: true
        default: 'default'

jobs:
  serve:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run serve_files script
      env:
        USER_TYPE: ${{ github.event.inputs.user_type }}
      run: |
        python serve_files.py
